### ISSUE TITLE
Provide binary artifact for use in Scala 2.8.0

### ISSUE THREAD

**Issue by helgoboss** [jorgeortiz85/scala-time#5]
I think now that Scala 2.8.0 is released, a lot of people will stick to it for a while. So it would be very useful to have a Scala 2.8.0 binary of scala-time in Maven Central.

**Comment by jorgeortiz85** [comment]
It's already there
http://repo1.maven.org/maven2/org/scala-tools/time/time_2.8.0/0.2/

**Comment by helgoboss** [comment]
Awesome, thanks. Sorry, I was not aware that there was already an existing issue for that.
